### ISSUE TITLE
Indirect memory leak

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1227]
Indirect leak of 1562 byte(s) in 66 object(s) allocated from:
    #0 0x55d5292f9d98 in __interceptor_malloc (/home/rcs/Test/zcash/zcash/src/test/test_bitcoin+0x14ed98)
    #1 0x55d5298b3fd4 in __os_malloc (/home/rcs/Test/zcash/zcash/src/test/test_bitcoin+0x708fd4)
    #2 0x41a61c978dc0ecff  (<unknown module>)

**Comment by daira** [comment]
Hmm, the stack trace isn't very informative here. Only 1562 bytes though.

**Comment by zebambam** [comment]
The test code leaks memory in the test executable only. It allocates on setup but doesn't deallocate on teardown. We could be specific and say "all test code has to pass all validators" but we're very far from that and I don't think that fixing that situation is a good use of time right now, I'd rather spend time spinning up various nodes on mainnet with validators on and get that clean first.
