### ISSUE TITLE
Least Authority Issue C: misaligned address for type 'uint32_t' in crypto/common.h:48

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1249]
There are a gazillion of these too.

```
crypto/common.h:48:22: runtime error: load of misaligned address 0x7f89b002c6d6 for type 'uint32_t', which requires 4 byte alignment
0x7f89b002c6d6: note: pointer points here
 2f f7 c3 23 6b 6b  66 1b 0a e4 e9 9b e6 7d  5b eb fc cf 4c 02 20 2d  36 4c dc 15 1c 6e e9 e9  e3 a0
             ^ 
    #0 0x55e6cac8d18e in ReadBE32 crypto/common.h:48
    #1 0x55e6cac8d18e in Transform crypto/sha256.cpp:53
    #2 0x55e6cac8d4ba in CSHA256::Write(unsigned char const*, unsigned long) crypto/sha256.cpp:156
    #3 0x55e6ca21bab5 in CHash256::Write(unsigned char const*, unsigned long) hash.h:33
    #4 0x55e6ca21bab5 in CHashWriter::write(char const*, unsigned long) hash.h:134
    #5 0x55e6ca21bab5 in void Serialize_impl<CHashWriter, unsigned char, std::allocator<unsigned char> >(CHashWriter&, std::vector<unsigned char, std::allocator<unsigned char> > const&, int, int, unsigned char const&) serialize.h:637
    #6 0x55e6ca21f3d5 in void Serialize<CHashWriter, unsigned char, std::allocator<unsigned char> >(CHashWriter&, std::vector<unsigned char, std::allocator<unsigned char> > const&, int, int) serialize.h:651
    #7 0x55e6ca21f3d5 in void Serialize<CHashWriter>(CHashWriter&, CScript const&, int, int) serialize.h:708
    #8 0x55e6ca21f3d5 in void SerReadWrite<CHashWriter, CScript>(CHashWriter&, CScript const&, int, int, CSerActionSerialize) serialize.h:908
    #9 0x55e6ca21f3d5 in void CTxIn::SerializationOp<CHashWriter, CSerActionSerialize>(CHashWriter&, CSerActionSerialize, int, int) primitives/transaction.h:186
    #10 0x55e6ca21f3d5 in void CTxIn::Serialize<CHashWriter>(CHashWriter&, int, int) const primitives/transaction.h:181
    #11 0x55e6ca21f3d5 in void Serialize<CHashWriter, CTxIn>(CHashWriter&, CTxIn const&, long, int) serialize.h:566
    #12 0x55e6ca21f3d5 in void Serialize_impl<CHashWriter, CTxIn, std::allocator<CTxIn>, CTxIn>(CHashWriter&, std::vector<CTxIn, std::allocator<CTxIn> > const&, int, int, CTxIn const&) serialize.h:645
    #13 0x55e6ca21f3d5 in void Serialize<CHashWriter, CTxIn, std::allocator<CTxIn> >(CHashWriter&, std::vector<CTxIn, std::allocator<CTxIn> > const&, int, int) serialize.h:651
    #14 0x55e6ca21f3d5 in void SerReadWrite<CHashWriter, std::vector<CTxIn, std::allocator<CTxIn> > >(CHashWriter&, std::vector<CTxIn, std::allocator<CTxIn> > const&, int, int, CSerActionSerialize) serialize.h:908
    #15 0x55e6ca21f3d5 in void CTransaction::SerializationOp<CHashWriter, CSerActionSerialize>(CHashWriter&, CSerActionSerialize, int, int) primitives/transaction.h:326
    #16 0x55e6ca21f3d5 in void CTransaction::Serialize<CHashWriter>(CHashWriter&, int, int) const primitives/transaction.h:320
    #17 0x55e6ca21f3d5 in void Serialize<CHashWriter, CTransaction>(CHashWriter&, CTransaction const&, long, int) serialize.h:566
    #18 0x55e6ca21f3d5 in CHashWriter& CHashWriter::operator<< <CTransaction>(CTransaction const&) hash.h:148
    #19 0x55e6ca21f3d5 in uint256 SerializeHash<CTransaction>(CTransaction const&, int, int) hash.h:158
    #20 0x55e6ca21f3d5 in CTransaction::UpdateHash() const primitives/transaction.cpp:121
    #21 0x55e6ca22125b in CTransaction::CTransaction(CMutableTransaction const&) primitives/transaction.cpp:129
    #22 0x55e6ca0a1b55 in signrawtransaction(std::vector<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&, bool) /home/bladen/Test/zcash/zcash/src/rpcrawtransaction.cpp:772
    #23 0x55e6c9ce8da6 in CRPCTable::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) const /home/bladen/Test/zcash/zcash/src/rpcserver.cpp:1025
    #24 0x55e6c9cea8fa in HTTPReq_JSONRPC /home/bladen/Test/zcash/zcash/src/rpcserver.cpp:950
    #25 0x55e6c9cea8fa in ServiceConnection(AcceptedConnection*) /home/bladen/Test/zcash/zcash/src/rpcserver.cpp:998
    #26 0x55e6c9ced486 in RPCAcceptHandler<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > /home/bladen/Test/zcash/zcash/src/rpcserver.cpp:563
    #27 0x55e6c9d71e01 in void boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> >::operator()<void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list1<boost::system::error_code const&> >(boost::_bi::type<void>, void (*&)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list1<boost::system::error_code const&>&, int) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/bind/bind.hpp:525
    #28 0x55e6c9d71e01 in void boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >::operator()<boost::system::error_code>(boost::system::error_code const&) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/bind/bind_template.hpp:47
    #29 0x55e6c9d71e01 in boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >, boost::system::error_code>::operator()() /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/bind_handler.hpp:47
    #30 0x55e6c9d71e01 in void boost::asio::asio_handler_invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >, boost::system::error_code> >(boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >, boost::system::error_code>&, ...) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/handler_invoke_hook.hpp:69
    #31 0x55e6c9d71e01 in void boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >, boost::system::error_code>, boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > > >(boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >, boost::system::error_code>&, boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > >&) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/handler_invoke_helpers.hpp:37
    #32 0x55e6c9d71e01 in boost::asio::detail::reactive_socket_accept_op<boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::ip::tcp, boost::_bi::bind_t<void, void (*)(boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > >, boost::asio::ssl::context&, bool, boost::shared_ptr<AcceptedConnection>, boost::system::error_code const&), boost::_bi::list5<boost::_bi::value<boost::shared_ptr<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> > > >, boost::reference_wrapper<boost::asio::ssl::context>, boost::_bi::value<bool>, boost::_bi::value<boost::shared_ptr<AcceptedConnectionImpl<boost::asio::ip::tcp> > >, boost::arg<1> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/reactive_socket_accept_op.hpp:123
    #33 0x55e6c9d1cf22 in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/task_io_service_operation.hpp:38
    #34 0x55e6c9d1cf22 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/impl/epoll_reactor.ipp:651
    #35 0x55e6c9d1f61e in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/task_io_service_operation.hpp:38
    #36 0x55e6c9d1f61e in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/impl/task_io_service.ipp:372
    #37 0x55e6c9d1f61e in boost::asio::detail::task_io_service::run(boost::system::error_code&) /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/detail/impl/task_io_service.ipp:149
    #38 0x55e6c9d2b8b6 in boost::asio::io_service::run() /home/bladen/Test/zcash/zcash/depends/x86_64-unknown-linux-gnu/include/boost/asio/impl/io_service.ipp:59
    #39 0x55e6ca85fc5c in thread_proxy (/home/bladen/Test/zcash/zcash/src/zcashd+0x2f64c5c)
    #40 0x7f89db5f26f9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76f9)
    #41 0x7f89db111b5c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x106b5c)
```

**Comment by daira** [comment]
OK, let's fix that to reduce false positives.

**Comment by daira** [comment]
https://github.com/bitcoin/bitcoin/pull/9512

**Comment by daira** [comment]
This is also Least Authority audit Issue C.
