### ISSUE TITLE
Ubuntu 16.04 - RPC Tests - Proxy_test.py Failed

### ISSUE THREAD

**Issue by cloudydata** [zcash/zcash#1968]
=== Running testscript proxy_test.py ===
    Traceback (most recent call last):
      File "/home/will/zcash/qa/rpc-tests/proxy_test.py", line 145, in <module>
        ProxyTest().main()
      File "/home/will/zcash/qa/rpc-tests/proxy_test.py", line 61, in __init__
        self.serv3 = Socks5Server(self.conf3)
      File "/home/will/zcash/qa/rpc-tests/test_framework/socks5.py", line 131, in __init__
        self.s.bind(conf.addr)
      File "/usr/lib/python2.7/socket.py", line 228, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 99] Cannot assign requested address
    !!! FAIL: proxy_test.py !!!

All other tests passed.

**Comment by arcalinea** [comment]
This looks like proxy_test is trying to bind to a port that is already in use, either because you ran the tests too quickly in succession, or something is already using that port.

You might try seeing what's running on the ports used in proxy_test. It looks like it's using ports 1234, 5443, and/or 8333. Try `netstat -tulpn | grep <port #>` to see what's running on those ports.

**Comment by arcalinea** [comment]
Closed since a few months have passed, feel free to re-open if issue recurs.
