### ISSUE TITLE
buildbot: `AttributeError: 'BuildNumberDirectoryUpload' object has no attribute 'checkWorkerVersion'`

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2374]
The coverage builder seems to have regressed from the Buildbot 0.9 upgrade: `AttributeError: 'BuildNumberDirectoryUpload' object has no attribute 'checkWorkerVersion'` from [this build log](https://ci.z.cash/#/builders/5/builds/4/steps/6/logs/err_text).

**Comment by nathan-at-least** [comment]
The new method is named `checkWorkerHasCommand`.

**Comment by ageis** [comment]
Fixed in private infrastructure PR: https://github.com/Electric-Coin-Company/infrastructure/pull/90

**Comment by nathan-at-least** [comment]
There's a new issue from that change as seen in [this coverage build](https://ci.z.cash/#/builders/5/builds/12/steps/6/logs/err_text):

```
Traceback (most recent call last):
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1357, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 572, in startStep
    self.results = yield self.run()
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 699, in run
    results = yield self.start()
  File "zcash_steps.py", line 56, in start
    'workdir': self._getWorkdir(),
  File "/home/bbmaster/venv/local/lib/python2.7/site-packages/buildbot/worker_transition.py", line 295, in __getattr__
    attr_name=name))
exceptions.AttributeError: 'BuildNumberDirectoryUpload' object has no attribute '_getWorkdir'
```

**Comment by nathan-at-least** [comment]
All of `coverage` builder now works: https://ci.z.cash/#/builders/5/builds/14
