### ISSUE TITLE
Segfault in memo data behavior

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#3250]
In #3206 at least one segfault was introduced.

```diff
-    for (CNotePlaintextEntry & entry : entries) {
-        z_inputs_.push_back(SendManyInputJSOP(entry.jsop, entry.plaintext.note(frompaymentaddress_), CAmount(entry.plaintext.value)));
-        std::string data(entry.plaintext.memo.begin(), entry.plaintext.memo.end());
+    for (CSproutNotePlaintextEntry & entry : entries) {
+        z_inputs_.push_back(SendManyInputJSOP(entry.jsop, entry.plaintext.note(frompaymentaddress_), CAmount(entry.plaintext.value())));
+        std::string data(entry.plaintext.memo().begin(), entry.plaintext.memo().end());
```

`memo()` is returning a fresh copy of a `boost::array` every time, so when it calls it twice and tries to get `begin()` and `end()` for each it's causing memory corruption issues because they're not guaranteed to be pointing to the same contiguous region of memory.

It should be returning a reference `boost::array<unsigned char, ZC_MEMO_SIZE>&` or maybe something else, not sure. Any place that calls `memo()` in that PR should be looked at to see if it's assuming the result is the same regardless of how many times `memo()` is called.

**Comment by bitcartel** [comment]
@ebfull How is the segfault triggered?  Reproducible?

**Comment by ebfull** [comment]
I was experiencing it when sending from a z-addr to another z-addr in regtest mode, as it went to `AsyncRPCOperation_sendmany::find_unspent_notes()`. It segfaulted on `std::string data(entry.plaintext.memo().begin(), entry.plaintext.memo().end());`

**Comment by ebfull** [comment]
part of my trace

```
Thread 6 "zcashd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed27b700 (LWP 21969)]
0x0000555555a117d5 in std::char_traits<char>::assign (__c2=<optimized out>, 
    __c1=@0x7fffa0021000: 0 '\000') at /usr/include/c++/7.3.1/bits/char_traits.h:285
285	      { __c1 = __c2; }
(gdb) bt
#0  0x0000555555a117d5 in std::char_traits<char>::assign (__c2=<optimized out>, 
    __c1=@0x7fffa0021000: 0 '\000') at /usr/include/c++/7.3.1/bits/char_traits.h:285
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars<unsigned char*> (__k2=0x7fffed279200 "", 
    __k1=0x7fffed298130 "\245\025\347\232[\024\303\314\330\vG\242\222\346\325V\371\031\317\305\033v\345Vn\357\022\034k\303\002\363H\204\\\033\262\231\261\026", 
    __p=0x7fffa0021000 "") at /usr/include/c++/7.3.1/bits/basic_string.h:368
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<unsigned char*> (__end=0x7fffed279200 "", 
    __beg=0x7fffed278e00 <incomplete sequence \366>, this=0x7fffed278de0)
    at /usr/include/c++/7.3.1/bits/basic_string.tcc:225
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<unsigned char*> (__end=<optimized out>, __beg=<optimized out>, 
    this=0x7fffed278de0) at /usr/include/c++/7.3.1/bits/basic_string.h:236
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<unsigned char*> (__end=<optimized out>, __beg=<optimized out>, 
    this=0x7fffed278de0) at /usr/include/c++/7.3.1/bits/basic_string.h:255
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<unsigned char*, void> (__a=..., __end=<optimized out>, 
    __beg=<optimized out>, this=0x7fffed278de0)
    at /usr/include/c++/7.3.1/bits/basic_string.h:607
#6  AsyncRPCOperation_sendmany::find_unspent_notes (this=this@entry=0x7fffac004f80)
    at wallet/asyncrpcoperation_sendmany.cpp:889
#7  0x0000555555a164a9 in AsyncRPCOperation_sendmany::main_impl (
    this=this@entry=0x7fffac004f80) at wallet/asyncrpcoperation_sendmany.cpp:230
#8  0x0000555555a1d245 in AsyncRPCOperation_sendmany::main (this=0x7fffac004f80)
    at wallet/asyncrpcoperation_sendmany.cpp:137
#9  0x000055555576464a in AsyncRPCQueue::run (this=0x55555640ec10, 
    workerId=<optimized out>) at asyncrpcqueue.cpp:68
#10 0x0000555555764ece in std::__invoke_impl<void, void (AsyncRPCQueue::*)(unsigned long), AsyncRPCQueue*, unsigned long> (__t=<optimized out>, __f=<optimized out>)
    at /usr/include/c++/7.3.1/bits/invoke.h:73
#11 std::__invoke<void (AsyncRPCQueue::*)(unsigned long), AsyncRPCQueue*, unsigned long> (__fn=<optimized out>) at /usr/include/c++/7.3.1/bits/invoke.h:95
#12 std::thread::_Invoker<std::tuple<void (AsyncRPCQueue::*)(unsigned long), AsyncRPCQueue*, unsigned long> >::_M_invoke<0ul, 1ul, 2ul> (this=<optimized out>)
    at /usr/include/c++/7.3.1/thread:234
#13 std::thread::_Invoker<std::tuple<void (AsyncRPCQueue::*)(unsigned long), AsyncRPCQueue*, unsigned long> >::operator() (this=<optimized out>)
    at /usr/include/c++/7.3.1/thread:243
#14 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (AsyncRPCQueue::*)(unsigned long), AsyncRPCQueue*, unsigned long> > >::_M_run (this=<optimized out>)
    at /usr/include/c++/7.3.1/thread:186

```
