### ISSUE TITLE
when we run z_gettotalbalance,t_addr is increasing automatically after some minutes? Can anybody explain this?

### ISSUE THREAD

**Issue by VtpVlan-oo7** [zcash/zcash#3420]
![screenshot from 2018-07-26 13 58 41](https://user-images.githubusercontent.com/31241756/43255472-86d5f776-90e7-11e8-9a75-e95a386075a9.png)

**Comment by coinsmith** [comment]
lol, please keep this updated.

**Comment by VtpVlan-oo7** [comment]
@garethtdavies ,i have done with gen=0   in .zcash/zcash.conf file.
But the same issue  transparent blance is automatic increasing. 
![screenshot from 2018-07-27 14 13 41](https://user-images.githubusercontent.com/31241756/43311363-df1a1f78-91a7-11e8-91ed-853f3918498e.png)

**Comment by coinsmith** [comment]
You should change it in the testnet subfolder configuration file, not in the .zcash folder.

**Comment by garethtdavies** [comment]
@VtpVlan-oo7 did you restart `zcashd` after making the change? What command are you using to start `zcashd` as command line options override config options? Failing that please post your `zcash.conf` file as gen=1 must be being set somewhere to enable mining.

**Comment by daira** [comment]
@coinsmith: that won't work; zcash.conf is looked for only in the top-level directory, not the network-specific one. (This is the same as Bitcoin Core.)

**Comment by VtpVlan-oo7** [comment]
@coinsmith thanks it is working..
but at this time i facing a new problem .

{ RpcError: 16: bad-txns-coinbase-spend-has-transparent-outputs
    at getRpcResult (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bitcoin-core/dist/src/parser.js:39:11)
    at Client.rpc (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bitcoin-core/dist/src/parser.js:82:14)
    at Client.tryCatcher (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/request/request.js:185:22)
    at emitTwo (events.js:131:20)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/vaibhav.verma/Desktop/zcashcoin/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: '16: bad-txns-coinbase-spend-has-transparent-outputs',
  code: -26,
  name: 'RpcError' }

**Comment by daira** [comment]
Because the coins in your account have been obtained by mining, they have to be spent to a shielded address. The ``z_shieldcoinbase`` call can be used to do this (run ``zcash-cli help z_shieldcoinbase`` to see its syntax.

**Comment by VtpVlan-oo7** [comment]
Why z_addr show invalid on explorer?

**Comment by garethtdavies** [comment]
Which explorer? See my reply here: https://github.com/zcash/zcash/issues/3423 - there are two testnet chains so likely you are using an explorer on a different chain.

**Comment by VtpVlan-oo7** [comment]
When we run sendRawTransaction method we find this error.
 RpcError: 16: bad-txns-vout-empty

**Comment by garethtdavies** [comment]
You'd have to provide more information as to how you constructed the transaction as this is where the error will be.

**Comment by ioptio** [comment]
Can you tell us exactly what command you're using?
