### ISSUE TITLE
error: uncaught exception: Error: number too large to retain precision - use readVarintBN

### ISSUE THREAD

**Issue by Smurfy303** [zcash/zcash#3445]
Hi,
I installed **zcash**(v1.1.2) and **zcash-bitcore-node** of npm package for json RPC call of version 3.1.3-rc2.
I started syncing by command `sudo zcash-bitcore-node start` which synced 99% but after that it throws me an error as below,

> You are mining with the default solver on 1 threads.
> 
> Since starting this node 39 seconds ago:
> - You have validated 5621 transactions!
> - You have completed 0 Equihash solver runs.
> 
> [Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
> [2018-08-03T05:28:57.722Z] **error: uncaught exception: Error: number too large to retain precision - use readVarintBN**
>     at BufferReader.readVarintNum (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferreader.js:127:15)
>     at BufferReader.readVarLengthBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferreader.js:139:18)
>     at Function.Input.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/input/input.js:95:28)
>     at Transaction.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction.js:320:23)
>     at Transaction.fromBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction.js:310:15)
>     at Transaction.fromString (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction.js:520:8)
>     at Bitcoin._zmqTransactionHandler (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:647:8)
>     at exports.Socket.<anonymous> (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:713:12)
>     at emitThree (events.js:136:13)
>     at exports.Socket.emit (events.js:217:7)
> [2018-08-03T05:28:57.724Z] **error: Error: number too large to retain precision - use readVarintBN**
>     at BufferReader.readVarintNum (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferreader.js:127:15)
>     at BufferReader.readVarLengthBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferreader.js:139:18)
>     at Function.Input.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/input/input.js:95:28)
>     at Transaction.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction.js:320:23)
>     at Transaction.fromBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:310:15)
>     at Transaction.fromString (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:520:8)
>     at Bitcoin._zmqTransactionHandler (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:647:8)
>     at exports.Socket.<anonymous> (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:713:12)
>     at emitThree (events.js:136:13)
>     at exports.Socket.emit (events.js:217:7)
> [2018-08-03T05:28:57.724Z] info: Beginning shutdown
> [2018-08-03T05:28:57.724Z] info: Stopping web
> [2018-08-03T05:28:57.725Z] info: Stopping bitcoind
> [2018-08-03T05:29:02.105Z] **error: uncaught exception: Error: number too large to retain precision - use readVarintBN**
>     at BufferReader.readVarintNum (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferread
> er.js:127:15)
>     at BufferReader.readVarLengthBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/buff
> erreader.js:139:18)
>     at Function.Input.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/in
> put/input.js:95:28)
>     at Transaction.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/trans
> action.js:320:23)
>     at Transaction.fromBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:310:15)
>     at Transaction.fromString (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:520:8)
>     at Bitcoin._zmqTransactionHandler (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:647:8)
>     at exports.Socket.<anonymous> (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:713:12)
>     at emitThree (events.js:136:13)
>     at exports.Socket.emit (events.js:217:7)
> [2018-08-03T05:29:02.106Z] **error: Error: number too large to retain precision - use readVarintBN**
>     at BufferReader.readVarintNum (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/bufferread
> er.js:127:15)
>     at BufferReader.readVarLengthBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/encoding/buff
> erreader.js:139:18)
>     at Function.Input.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/in
> put/input.js:95:28)
>     at Transaction.fromBufferReader (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/trans
> action.js:320:23)
>     at Transaction.fromBuffer (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:310:15)
>     at Transaction.fromString (/usr/local/lib/node_modules/zcash-bitcore-node/node_modules/zcash-bitcore-lib/lib/transaction/transaction
> .js:520:8)
>     at Bitcoin._zmqTransactionHandler (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:647:8)
>     at exports.Socket.<anonymous> (/usr/local/lib/node_modules/zcash-bitcore-node/lib/services/bitcoind.js:713:12)
>     at emitThree (events.js:136:13)
>     at exports.Socket.emit (events.js:217:7)
> [2018-08-03T05:29:02.106Z] info: Beginning shutdown
> [2018-08-03T05:29:02.107Z] info: Stopping web
> [2018-08-03T05:29:02.107Z] info: Stopping bitcoind
> [2018-08-03T05:29:02.408Z] warn: ZMQ disconnect: tcp://127.0.0.1:28234
> [2018-08-03T05:29:02.409Z] warn: ZMQ connection delay: tcp://127.0.0.1:28234
> [2018-08-03T05:29:02.910Z] warn: ZMQ connection delay: tcp://127.0.0.1:28234
> [2018-08-03T05:29:02.910Z] warn: ZMQ connection delay: tcp://127.0.0.1:28234
> [2018-08-03T05:29:02.910Z] warn: ZMQ connection delay: tcp://127.0.0.1:28234
> 

I am in last stage towards zcash sync success . Please, anyone could help me to sort this ??

**Comment by ioptio** [comment]
@ianamunoz any input on this one?

**Comment by Smurfy303** [comment]
Sorry but I am not getting **overwinter** word meaning

**Comment by ioptio** [comment]
@Smurfy303 have you tried the suggestions above?

**Comment by Smurfy303** [comment]
Actully I also installed **npm install -g bitcore** library for Bitcoin on my server. I afraid to to try your suggestion because if it overrides .bitcore folder then it will start syncing again which takes more than 8 days.

**Comment by ioptio** [comment]
@Smurfy303 you can backup your blocks folder and try again. This is outside the realm of our official support, though. I'd suggest trying to get community support in https://chat.zcashcommunity.com or https://forum.z.cash

**Comment by hoffmabc** [comment]
Is this actually resolved? I really don't see how this is fixed... :(

**Comment by hoffmabc** [comment]
Even using the repo mentioned above that's been upgraded I see

```
Since starting this node 30 seconds ago:
           Block height | 404099
            Connections | 0
  Network solution rate | 1896334436 Sol/s

You are currently not mining.
To enable mining, add 'gen=1' to your zcash.conf and restart.

Since starting this node 32 seconds ago:
- You have validated 1769 transactions!

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
[2018-10-02T18:05:45.814Z] error: uncaught exception: [Error: number too large to retain precision - use readVarintBN]
[2018-10-02T18:05:45.817Z] error: Error: number too large to retain precision - use readVarintBN
    at BufferReader.readVarintNum (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:127:15)
    at BufferReader.readVarLengthBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:139:18)
    at Function.Input.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)
    at Transaction.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)
    at Transaction.fromBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:77:13)
    at Bitcoin.emit (events.js:169:7)
    at Bitcoin._zmqTransactionHandler (/home/bitcore/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)
    at null.<anonymous> (/home/bitcore/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:713:12)
[2018-10-02T18:05:45.817Z] info: Beginning shutdown
[2018-10-02T18:05:45.818Z] info: Stopping insight-ui
[2018-10-02T18:05:45.818Z] info: Stopping insight-api
[2018-10-02T18:05:45.818Z] info: Stopping web
[2018-10-02T18:05:45.819Z] info: Stopping bitcoind
[2018-10-02T18:05:45.963Z] error: uncaught exception: { [bitcore.ErrorInvalidState: Invalid state: Invalid length while reading varlength buffer. Expected to read: 246 and read 152]
  message: 'Invalid state: Invalid length while reading varlength buffer. Expected to read: 246 and read 152',
  stack: 'Invalid state: Invalid length while reading varlength buffer. Expected to read: 246 and read 152\nError\n    at Error.NodeError (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/errors/index.js:20:41)\n    at Object.module.exports.checkState (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)\n    at BufferReader.readVarLengthBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:141:5)\n    at Function.Input.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)\n    at Transaction.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)\n    at Transaction.fromBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)\n    at InsightAPI.transactionEventHandler (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/lib/index.js:267:30)\n    at emitOne (events.js:77:13)\n    at Bitcoin.emit (events.js:169:7)\n    at Bitcoin._zmqTransactionHandler (/home/bitcore/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)' }
[2018-10-02T18:05:45.965Z] error: Invalid state: Invalid length while reading varlength buffer. Expected to read: 246 and read 152
Error
    at Error.NodeError (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.module.exports.checkState (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)
    at BufferReader.readVarLengthBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:141:5)
    at Function.Input.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)
    at Transaction.fromBufferReader (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)
    at Transaction.fromBuffer (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/home/bitcore/bitcore-node-zcash/zcash/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:77:13)
    at Bitcoin.emit (events.js:169:7)
    at Bitcoin._zmqTransactionHandler (/home/bitcore/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)
[2018-10-02T18:05:45.965Z] info: Beginning shutdown
[2018-10-02T18:05:45.965Z] info: Stopping insight-ui
[2018-10-02T18:05:45.966Z] info: Stopping insight-api
[2018-10-02T18:05:45.966Z] info: Stopping web
[2018-10-02T18:05:45.966Z] info: Stopping bitcoind
[2018-10-02T18:05:45.979Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
[2018-10-02T18:05:46.479Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2018-10-02T18:05:46.479Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2018-10-02T18:05:46.480Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
```

**Comment by braddmiller** [comment]
Following the details of this Dockerfile will launch a functioning insight explorer based on zcashd 2.0.2.

https://github.com/zcash-hackworks/zcash-insight-explorer

The npm package `zcash-bitcore-node` is no longer maintained as far as I can tell.
