### ISSUE TITLE
[zcash-hackworks/bitcore-lib-zcash] parsing from hexadecimal is not correct

### ISSUE THREAD

**Issue by karel-3d** [zcash/zcash#3636]
(this is related to https://github.com/zcash-hackworks/bitcore-lib-zcash/ , but that doesn't have enabled issues, I was told to write it here)

Parsing transaction from hexadecimal is not working correctly.

Easy way to reproduce:

```
var str = [copy-paste test vector 1 from https://github.com/zcash/zips/blob/master/zip-0243.rst]
var Tx = require('./lib/transaction');
var t = new Tx(str);
console.log(t.joinSplits[0].vpub_old); // correctly writes 0
console.log(t.joinSplits[1].vpub_old); // writes 10786314384656855000 as the position of the reader is wrong on joinSplits[1] reader at that point
```

I am investigating where exactly is the bug. The repo has a commit that says "support for sapling" and it seems to be reading the fields, but there is a bug somewhere.

**Comment by karel-3d** [comment]
It is implemented correctly in bitgo repo

https://github.com/BitGo/bitgo-utxo-lib/commit/7af0fc184b51003418e00ceb438e7b71639ba9e9#diff-42d8d2088a96641b563b25ad908b0c0fR156

**Comment by radix42** [comment]
ah, this would probably be why my testnet Insight instance crashed when I clicked on a transaction that had a shielded txn :-(

also working on other troubles with Insight rn

**Comment by karel-3d** [comment]
yep that's very probably the reason.

**Comment by radix42** [comment]
I just got the traceback for the crash in my testnet Insight node:

```
[2018-10-27T13:28:57.126Z] error: RangeError: index out of range
    at checkOffset (buffer.js:700:11)
    at Buffer.readUInt32LE (buffer.js:762:5)
    at BufferReader.readUInt64LEBN (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/insight-api-zcash/node_modules/bitcore-lib-zcash/lib/encoding/bufferreader.js:94:25)
    at Function.JSDescription.fromBufferReader (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/insight-api-zcash/node_modules/bitcore-lib-zcash/lib/transaction/jsdescription.js:159:24)
    at Transaction.fromBufferReader (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/insight-api-zcash/node_modules/bitcore-lib-zcash/lib/transaction/transaction.js:402:42)
    at Transaction.fromBuffer (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/insight-api-zcash/node_modules/bitcore-lib-zcash/lib/transaction/transaction.js:350:15)
    at InsightAPI.transactionEventHandler (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/insight-api-zcash/lib/index.js:278:30)
    at emitOne (events.js:77:13)
    at Bitcoin.emit (events.js:169:7)
    at Bitcoin._zmqTransactionHandler (/home/djm/zcash-block-explorer/zcash-explorer/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)
```

**Comment by radix42** [comment]
block 321746 is the last one in the debug.log before it shutdown  Insight stopped it on the above error)

**Comment by radix42** [comment]
oopsie, I think I just crashed the official testnet explorer by hitting the same bug
https://www.dropbox.com/s/xldxdvso710mxe5/Screenshot%202018-10-28%2010.02.01.png?dl=0

**Comment by radix42** [comment]
@bitcartel does the above data help you in figuring out what is making Insight blow up on Sapling?

**Comment by radix42** [comment]
something in bitcore-lib-zcash/lib/transaction/transaction.js isn't right :-(

**Comment by bitcartel** [comment]
@radix42 testnet explorer is at 323530 https://explorer.testnet.z.cash/block/000001072f77b04fd809365ac17305c3713934fb0622457bd27c434d9cd3e817

Here are some sample tx:

Sapling zaddr->zaddr: https://explorer.testnet.z.cash/tx/abbd823cbd3d4e3b52023599d81a96b74817e95ce5bb58354f979156bd22ecc8

Sprout Zaddr unshielding to Taddr: https://explorer.testnet.z.cash/tx/07c8f229a9468f7fd3446c36ed92c7f412a55e02c6b4d26f333b63d3ba6356bd

Taddr shielding to Sapling Zaddr: https://explorer.testnet.z.cash/tx/dda3941da3ab77f3bdc61728354e6e9285c31e456f38b4cc39278ff5c3e7d0fd

**Comment by radix42** [comment]
lemme find a block/txn that was making it blow up earlier today

**Comment by radix42** [comment]
go to https://explorer.testnet.z.cash/block/000000f6318d9320ebb211b4835fc6bc50401734488182120092c2e81320f346 and then click the "Next block" link to block 321747 to reproduce the crash

**Comment by bitcartel** [comment]
@radix42 Fixed the testnet explorer and pushed a commit to the zcash-hackworks/bitcore-lib-zcash repository.  The issue was that once Sapling activates, JoinSplits change to usings Groth16 proofs which are a different size.

**Comment by radix42** [comment]
now the TODO list is down to the blocks (plural!) api endpoint returning a 400 because a method is not found, and charts being busted 😢
