### ISSUE TITLE
bitcore-lib-zcash: "TypeError: bn.toBuffer is not a function"

### ISSUE THREAD

**Issue by LitecoinZ** [zcash/zcash#3776]
Hi,
creating a sapling transaction using bitcore-lib-zcash I have this error:

```
TypeError: bn.toBuffer is not a function
    at BufferWriter.writeUInt64LEBN (/home/litecoinz/insight/zcash/bitcore-lib-zcash/lib/encoding/bufferwriter.js:89:16)
    at Transaction.toBufferWriter (/home/litecoinz/insight/zcash/bitcore-lib-zcash/lib/transaction/transaction.js:319:12)
    at Transaction.toBuffer (/home/litecoinz/insight/zcash/bitcore-lib-zcash/lib/transaction/transaction.js:287:15)
    at Transaction.uncheckedSerialize.Transaction.toString (/home/litecoinz/insight/zcash/bitcore-lib-zcash/lib/transaction/transaction.js:164:15)
    at Object.<anonymous> (/home/litecoinz/insight/zcash/bitcore-lib-zcash/test.js:19:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

This is the content of my `test.js` I used:

```
const zec = require('.')
let transaction = new zec.Transaction()
transaction.version = 4
transaction.fOverwintered = true
transaction.nVersionGroupId = 0x85202f89
transaction.nExpiryHeight = 384561
transaction.valueBalance = 0

var privateKey = 'L1Gbxmd8PLerALAgKgdt73YRMqBJ2z1T3oRSprre2xCY6nvNHVRu'
let utxo = {
  txId: "654e4c946205a1a685e1ccf6b7f985b2da9f7112a60e4cab9f5e5c09d6c1c0ab",
  outputIndex: 0,
  script: "76a914149905316a9cccde5e5db3a97c156f66198e6a0a88ac",
  satoshis: 1020000
}
transaction.from(utxo).to("t1atmCquPaeJ4jRREbutauqGh58fyMBthYy", 1010000)
  .sign(privateKey)
```

I have fixed this issue with the following patch:

```
diff --git a/lib/encoding/bufferwriter.js b/lib/encoding/bufferwriter.js
index 7967c53..e45d6f2 100644
--- a/lib/encoding/bufferwriter.js
+++ b/lib/encoding/bufferwriter.js
@@ -79,6 +79,14 @@ BufferWriter.prototype.writeUInt32LE = function(n) {
   return this;
 };
 
+BufferWriter.prototype.writeUInt64LE = function(n) {
+  var buf = new Buffer(8);
+  buf.writeInt32LE(n & -1, 0);
+  buf.writeUInt32LE(Math.floor(n / 0x100000000), 4);
+  this.write(buf);
+  return this;
+};
+
 BufferWriter.prototype.writeUInt64BEBN = function(bn) {
   var buf = bn.toBuffer({size: 8});
   this.write(buf);
diff --git a/lib/transaction/transaction.js b/lib/transaction/transaction.js
index af90a0a..7d8dcfa 100644
--- a/lib/transaction/transaction.js
+++ b/lib/transaction/transaction.js
@@ -316,7 +316,7 @@ Transaction.prototype.toBufferWriter = function(writer) {
   }
 
   if (this.version >= 4) {
-    writer.writeUInt64LEBN(this.valueBalance);
+    writer.writeUInt64LE(this.valueBalance);
     writer.writeVarintNum(this.spendDescs.length);
     _.each(this.spendDescs, function(desc) {
       desc.toBufferWriter(writer);
```

Could someone check if my solution is correct or if need another way to fix this issue?

Thanks,
Mark

**Comment by ioptio** [comment]
This library isn't officially supported for creating transactions at this time. We'll keep this open, though.

**Comment by LitecoinZ** [comment]
Ok @ioptio . Please, take in mind that creating transactions is very important for 3rd party integrations with bitcore based software like copay.

I hope you or someone that is maintaining bitcore-lib-zcash could fix it soon.
 
Thanks

**Comment by LitecoinZ** [comment]
Sapling Transaction Signature support has been added to bitcore-lib https://github.com/LitecoinZ-Community/bitcore-lib-ltz
Tomorrow I will create a PR with required changes

**Comment by Snowgem** [comment]
you can easily fix this with this initialization
var DEFAULT_VALUEBALANCE = new BN(0); instead of var DEFAULT_VALUEBALANCE = 0;
