### ISSUE TITLE
sprout_sapling_migration.py test fails with '--enable-debug'

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4275]
### Describe the issue
sprout_sapling_migration.py test fails with '--enable-debug'.

### Can you reliably reproduce the issue?

`Always`

#### If so, please list the steps to reproduce below:
1. `CONFIGURE_FLAGS='--enable-debug' zcutil/build.sh`
2. `./qa/pull-tester/rpc-tests.sh sprout_sapling_migration.py`

### Expected behaviour
Test passes.

### Actual behaviour + errors
Test fails and `zcashd` crashes.

### The version of Zcash you were using:

`Zcash Daemon version v2.1.0-1-1d2c747af`

### Machine specs:
- OS name + version: `macOS 10.15.3 (19D49f)`
- CPU: `6-Core Intel Core i7 2,6 GHz`
- RAM: `16 GB`
- Disk size: `498,89 GB`
- Disk Type (HD/SDD): `SSD`
- Linux kernel version (uname -a): `Darwin Kernel Version 19.3.0: Sun Dec  8 22:27:29 PST 2019; root:xnu-6153.80.8.0.1~15/RELEASE_X86_64 x86_64`
- Compiler version (gcc --version): `Apple clang version 11.0.0 (clang-1100.0.33.16)`
- Linker version (ld -v): `@(#)PROGRAM:ld  PROJECT:ld64-530`
- Assembler version (as --version): `clang version 9.0.0 (tags/RELEASE_900/final)`

### Any extra information that might be useful in the debugging process.
[sprout_sapling_migration.py.log](https://github.com/zcash/zcash/files/3993159/sprout_sapling_migration.py.log)
[zcashd_2019-12-23-014632_MacBook-Pro-2018.log](https://github.com/zcash/zcash/files/3993160/zcashd_2019-12-23-014632_MacBook-Pro-2018.log)

**Comment by rex4539** [comment]
```
Assertion failed: (onlyMaybeDeadlock), function potential_deadlock_detected, file sync.cpp, line 112.
Unexpected exception caught during testing: [Errno 61] Connection refused
```

**Comment by zancas** [comment]
Hey here's the same test on the same branch failing in a "bullseye/sid" debian container:

```BASH
rm -rf cache/ && ./qa/pull-tester/rpc-tests.sh sprout_sapling_migration
=== Running testscript sprout_sapling_migration.py ===
Initializing test directory /tmp/testih6mmsbb
Running test using '-migrationdestaddress'...
Mining blocks...
waiting for async operation opid-d65b6adf-88e7-4487-aa7f-3c4c5236f006
Mining to block 494 % 500...
migration operation: [{'id': 'opid-44b04eea-24b6-4d1d-8945-ac19bbfbf460', 'status': 'executing', 'creation_time': 1577059038, 'method': 'saplingmigration', 'target_height': 500}]
waiting for async operation opid-44b04eea-24b6-4d1d-8945-ac19bbfbf460
result: {'id': 'opid-44b04eea-24b6-4d1d-8945-ac19bbfbf460', 'status': 'success', 'creation_time': 1577059038, 'result': {'num_tx_created': 1, 'amount_migrated': '5.0999', 'migration_txids': ['0475ae647c4b9e1f732b4cd0c78a92f7fcc006e44aa1691ef07c59af81f07de6']}, 'execution_secs': Decimal('35.117802439'), 'method': 'saplingmigration', 'target_height': 500}
mempool: ['0475ae647c4b9e1f732b4cd0c78a92f7fcc006e44aa1691ef07c59af81f07de6']
status: {'enabled': True, 'destination_address': 'zregtestsapling1ssqj3f3majnl270985gqcdqedd9t4nlttjqskccwevj2v20sc25deqspv3masufnwcdy67cydyy', 'unmigrated_amount': '4.90', 'unfinalized_migrated_amount': '5.0999', 'finalized_migrated_amount': '0.00', 'finalized_migration_transactions': 0, 'migration_txids': ['0475ae647c4b9e1f732b4cd0c78a92f7fcc006e44aa1691ef07c59af81f07de6']}
sprout balance: 4.90000000, sapling balance: 5.09990000
Running test using default Sapling address...
Mining blocks...
waiting for async operation opid-dfac720b-f9fe-4b53-ae5b-404770d5e1b5
Mining to block 494 % 500...
migration operation: [{'id': 'opid-42a9d64e-fc35-495f-af29-6e5336c4c2f1', 'status': 'executing', 'creation_time': 1577059153, 'method': 'saplingmigration', 'target_height': 1000}]
waiting for async operation opid-42a9d64e-fc35-495f-af29-6e5336c4c2f1
result: {'id': 'opid-42a9d64e-fc35-495f-af29-6e5336c4c2f1', 'status': 'success', 'creation_time': 1577059153, 'result': {'num_tx_created': 1, 'amount_migrated': '0.6999', 'migration_txids': ['3d0a9cf37d1e59eb8d9655d510d5fcb8eac70ec96866a0deeafb8e602fb865a1']}, 'execution_secs': Decimal('33.321706455'), 'method': 'saplingmigration', 'target_height': 1000}
mempool: ['3d0a9cf37d1e59eb8d9655d510d5fcb8eac70ec96866a0deeafb8e602fb865a1']
Assertion failed: Unconfirmed sapling balance at 499 % 500
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py", line 203, in run_test
    self.run_migration_test(self.nodes[1], sproutAddr1, saplingAddr1, 1000)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py", line 128, in run_migration_test
    assert_true(node.z_getbalance(saplingAddr, 0) > Decimal('0'), "Unconfirmed sapling balance at 499 % 500")
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/util.py", line 392, in assert_true
    raise AssertionError(message)
Stopping nodes
Cleaning up
Failed
!!! FAIL: sprout_sapling_migration.py (233s) !!!



Tests completed: 1
successes 0; failures: 1

Failing tests: sprout_sapling_migration.py
```

**Comment by zancas** [comment]
Check this out, it passes with [this breakpoint](https://github.com/zancas/zcash/blob/c2e8e690f34b0264ce10a5a03778cc3ad262dcb1/qa/rpc-tests/sprout_sapling_migration.py#L128) added:

```BASH
rm -rf cache/ && ./qa/pull-tester/rpc-tests.sh sprout_sapling_migration
=== Running testscript sprout_sapling_migration.py ===
Initializing test directory /tmp/testr609grwd
Running test using '-migrationdestaddress'...
Mining blocks...
waiting for async operation opid-87b10ca1-c2cb-4bd1-bbb6-214f1249179c
Mining to block 494 % 500...
migration operation: [{'id': 'opid-f06df42d-1e51-4c23-8f01-ff7b7713588e', 'status': 'executing', 'creation_time': 1577059577, 'method': 'saplingmigration'
, 'target_height': 500}]
waiting for async operation opid-f06df42d-1e51-4c23-8f01-ff7b7713588e
result: {'id': 'opid-f06df42d-1e51-4c23-8f01-ff7b7713588e', 'status': 'success', 'creation_time': 1577059577, 'result': {'num_tx_created': 1, 'amount_migr
ated': '0.2699', 'migration_txids': ['9d88ccab4f0316055c87bd7a4ce1dca59a49ab8d00a4ceae130d893541f0bb55']}, 'execution_secs': Decimal('33.490191246'), 'met
hod': 'saplingmigration', 'target_height': 500}
mempool: ['9d88ccab4f0316055c87bd7a4ce1dca59a49ab8d00a4ceae130d893541f0bb55']
> /home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py(129)run_migration_test()
-> assert_true(node.z_getbalance(saplingAddr, 0) > Decimal('0'), "Unconfirmed sapling balance at 499 % 500")
(Pdb) c
status: {'enabled': True, 'destination_address': 'zregtestsapling1ssqj3f3majnl270985gqcdqedd9t4nlttjqskccwevj2v20sc25deqspv3masufnwcdy67cydyy', 'unmigrate
d_amount': '9.73', 'unfinalized_migrated_amount': '0.2699', 'finalized_migrated_amount': '0.00', 'finalized_migration_transactions': 0, 'migration_txids':
 ['9d88ccab4f0316055c87bd7a4ce1dca59a49ab8d00a4ceae130d893541f0bb55']}
sprout balance: 9.73000000, sapling balance: 0.26990000
Running test using default Sapling address...
Mining blocks...
waiting for async operation opid-f4325658-c5c6-4559-becc-251558e84da0
Mining to block 494 % 500...
migration operation: [{'id': 'opid-6e56900f-6007-431c-a827-639acbe86dc1', 'status': 'executing', 'creation_time': 1577059726, 'method': 'saplingmigration'
, 'target_height': 1000}]
waiting for async operation opid-6e56900f-6007-431c-a827-639acbe86dc1
result: {'id': 'opid-6e56900f-6007-431c-a827-639acbe86dc1', 'status': 'success', 'creation_time': 1577059726, 'result': {'num_tx_created': 1, 'amount_migr
ated': '9.0999', 'migration_txids': ['3acd509bf741393f989c6832a8fb2818d2dd0b5379dffc8e1fed8b7cacb8bf15']}, 'execution_secs': Decimal('30.35314123'), 'meth
od': 'saplingmigration', 'target_height': 1000}
mempool: ['3acd509bf741393f989c6832a8fb2818d2dd0b5379dffc8e1fed8b7cacb8bf15']
> /home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py(129)run_migration_test()
-> assert_true(node.z_getbalance(saplingAddr, 0) > Decimal('0'), "Unconfirmed sapling balance at 499 % 500")
(Pdb) c
status: {'enabled': True, 'destination_address': 'zregtestsapling1400y4r2srfehd69xr9cy2f4fhh9zkgs09l2l24yvam0gtdnnz5satfs0f9gaxezklttcu2sl6zy', 'unmigrate
d_amount': '0.90', 'unfinalized_migrated_amount': '9.0999', 'finalized_migrated_amount': '0.00', 'finalized_migration_transactions': 0, 'migration_txids':
 ['3acd509bf741393f989c6832a8fb2818d2dd0b5379dffc8e1fed8b7cacb8bf15']}
sprout balance: 0.90000000, sapling balance: 9.09990000
Stopping nodes
Cleaning up
Tests successful
--- Success: sprout_sapling_migration.py (298s) ---



Tests completed: 1
```

**Comment by zancas** [comment]
Hypothesis:   The component queried by `node.z_getbalance` is not updated quickly enough to be synced with the state change caused by the generation of a new block.

I think this would be fixed if all the state changes implied by a block generation were guaranteed to happen atomically?

**Comment by zancas** [comment]
I _think_ the other intermittent fails I've observed may be in the same class...

**Comment by zancas** [comment]
OK, here's a first step towards detecting-isolating a race condition:

https://github.com/zancas/zcash/tree/4275_detect_race

**Comment by zancas** [comment]
I'm going to open a PR between that branch and the 4074 Python port, to help publish what the test entails.

**Comment by zancas** [comment]
Several other tests fail intermittently, is there a common root cause?

One such test is `wallet_listnotes.py`.

I copied the test to `detect_race.py`, and removed lines subsequent to an intermittently failing assertion.

I'd really like to know if it fails at all on Mac OS, and if it does, what the error message is.

@rex4539 is there any chance you can run this test:

https://github.com/zancas/zcash/blob/4275_detect_race/qa/rpc-tests/detect_race.py

?

It only fails intermittently so, you might have to run it several times to generate an interesting failure...

Also, I print the return value of `wait_and_assert_operationid_status` on the hypothesis that it might return `None` when the test fails, but I don't observe that correlation.

**Comment by rex4539** [comment]
Had to run it more than 10 times but got it to fail.

```
=== Running testscript detect_race.py ===
Initializing test directory /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/testympi4iq_
waiting for async operation opid-817e2f6c-e735-49eb-9ac4-2c2c5f486d0d
txid_1 is: 09228eecd85cb7a9ca9689c0083127f471b29e3dac5925e490f33740fd17301f
Assertion failed: (left == right)
  left: <1>
 right: <0>
  File "/Users/rex/rex4539-zancas-rpc-tests/qa/rpc-tests/test_framework/test_framework.py", line 122, in main
    self.run_test()
  File "/Users/rex/rex4539-zancas-rpc-tests/qa/rpc-tests/detect_race.py", line 50, in run_test
    assert_equal(1, len(unspent_cb))
  File "/Users/rex/rex4539-zancas-rpc-tests/qa/rpc-tests/test_framework/util.py", line 388, in assert_equal
    raise AssertionError("(left == right)%s\n  left: <%s>\n right: <%s>" % (message, str(expected), str(actual)))
Stopping nodes
Cleaning up
Failed
!!! FAIL: detect_race.py (90s) !!!
```

**Comment by zancas** [comment]
@rex4539 thanks!   So you didn't get the `(onlyMaybeDeadlock)` so I'll make this a separate issue.

**Comment by zancas** [comment]
OK, so there's a separate issue #4276 that is tracking intermittent failures.

Now I'll run `sprout_sapling_merge.py` in a loop...  to get a bit more data on its behavior.

**Comment by zancas** [comment]
Per @mdr0id 's request here are some `sapling_sprout_migration` run logs.
[20191226_run.txt](https://github.com/zcash/zcash/files/4006136/20191226_run.txt)
[sprout_sapling_merge_looped_output.txt](https://github.com/zcash/zcash/files/4006137/sprout_sapling_merge_looped_output.txt)

**Comment by zancas** [comment]
@rex4539 because I generated the below error in a Debian environment we should change the name of this issue.

```BASH
=== Running testscript sprout_sapling_migration.py ===                                                         [51/1903]
Initializing test directory /tmp/testulbszauh
Running test using '-migrationdestaddress'...
Mining blocks...
waiting for async operation opid-43ff8de0-d60e-426a-8a63-30f7c0fe5f4f
Mining to block 494 % 500...
migration operation: [{'id': 'opid-285708ef-ca3d-478c-9f57-9aede14564ca', 'status': 'executing', 'creation_time': 157756
2221, 'method': 'saplingmigration', 'target_height': 500}]
waiting for async operation opid-285708ef-ca3d-478c-9f57-9aede14564ca
result: {'id': 'opid-285708ef-ca3d-478c-9f57-9aede14564ca', 'status': 'success', 'creation_time': 1577562221, 'result':
{'num_tx_created': 1, 'amount_migrated': '0.1999', 'migration_txids': ['672594041f10b60bfd745520377a411a15edbbc44951c7c2
3cc51a61665965a7']}, 'execution_secs': Decimal('36.485385061'), 'method': 'saplingmigration', 'target_height': 500}
zcashd: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack
&): Assertion `onlyMaybeDeadlock' failed.
Unexpected exception caught during testing: [Errno 111] Connection refused
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py", line 188, in run_test
    self.run_migration_test(self.nodes[0], sproutAddr0, SAPLING_ADDR, 500)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py", line 120, in run_migration_test
    self.sync_all()
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/test_framework.py", line 76, in sync_all
    sync_blocks(self.nodes)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/util.py", line 53, in sync_blocks
    counts = [ x.getblockcount() for x in rpc_connections ]
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/util.py", line 53, in <listcomp>
    counts = [ x.getblockcount() for x in rpc_connections ]
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/authproxy.py", line 132, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/authproxy.py", line 118, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
Stopping nodes
Traceback (most recent call last):
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/sprout_sapling_migration.py", line 207, in <module>
    SproutSaplingMigration().main()
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/test_framework.py", line 137, in main
    stop_nodes(self.nodes)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/util.py", line 253, in stop_nodes
    node.stop()
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/authproxy.py", line 132, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/pherder/zcashes/python_upgrade/qa/rpc-tests/test_framework/authproxy.py", line 108, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1255, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.7/http/client.py", line 1108, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
!!! FAIL: sprout_sapling_migration.py (165s) !!!
```

**Comment by rex4539** [comment]
```
=== Running testscript sprout_sapling_migration.py ===
Initializing test directory /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/testXUT4m4
Running test using '-migrationdestaddress'...
Mining blocks...
waiting for async operation opid-3b6df921-f6e4-4b81-92e3-4dafe9e22f0e
Mining to block 494 % 500...
migration operation: [{u'status': u'executing', u'creation_time': 1578310141, u'id': u'opid-2f449bc7-0c7b-4a67-864f-34816a5a494c', u'target_height': 500, u'method': u'saplingmigration'}]
waiting for async operation opid-2f449bc7-0c7b-4a67-864f-34816a5a494c
result: {u'status': u'success', u'execution_secs': Decimal('12.961895'), u'creation_time': 1578310141, u'id': u'opid-2f449bc7-0c7b-4a67-864f-34816a5a494c', u'result': {u'amount_migrated': u'3.2999', u'migration_txids': [u'7d26f2da4eb160b30f9b5c29dd032a56fa41c2206126dd727aca08fd955e6ddc'], u'num_tx_created': 1}, u'target_height': 500, u'method': u'saplingmigration'}
mempool: [u'7d26f2da4eb160b30f9b5c29dd032a56fa41c2206126dd727aca08fd955e6ddc']
status: {u'migration_txids': [u'7d26f2da4eb160b30f9b5c29dd032a56fa41c2206126dd727aca08fd955e6ddc'], u'finalized_migrated_amount': u'0.00', u'unfinalized_migrated_amount': u'3.2999', u'enabled': True, u'unmigrated_amount': u'6.70', u'finalized_migration_transactions': 0, u'destination_address': u'zregtestsapling1ssqj3f3majnl270985gqcdqedd9t4nlttjqskccwevj2v20sc25deqspv3masufnwcdy67cydyy'}
sprout balance: 6.70000000, sapling balance: 3.29990000
Running test using default Sapling address...
Mining blocks...
waiting for async operation opid-115bbde2-4601-47eb-9f7e-638e543dbe39
Mining to block 494 % 500...
migration operation: [{u'status': u'executing', u'creation_time': 1578310216, u'id': u'opid-8f49f50a-502b-4ea8-8785-697be49c2359', u'target_height': 1000, u'method': u'saplingmigration'}]
waiting for async operation opid-8f49f50a-502b-4ea8-8785-697be49c2359
result: {u'status': u'success', u'execution_secs': Decimal('13.135584'), u'creation_time': 1578310216, u'id': u'opid-8f49f50a-502b-4ea8-8785-697be49c2359', u'result': {u'amount_migrated': u'3.1999', u'migration_txids': [u'87e3a711d5697e4439fc9131ed5728f8f584e51946d426d3b882680a76eb5193'], u'num_tx_created': 1}, u'target_height': 1000, u'method': u'saplingmigration'}
mempool: [u'87e3a711d5697e4439fc9131ed5728f8f584e51946d426d3b882680a76eb5193']
status: {u'migration_txids': [u'87e3a711d5697e4439fc9131ed5728f8f584e51946d426d3b882680a76eb5193'], u'finalized_migrated_amount': u'0.00', u'unfinalized_migrated_amount': u'3.1999', u'enabled': True, u'unmigrated_amount': u'6.80', u'finalized_migration_transactions': 0, u'destination_address': u'zregtestsapling1mw4ksymnrslv2mhy973d9pp99253rel5g8apepfjkhp7saefu37cmdhnfvxfd8faqmqdvtmlnet'}
sprout balance: 6.80000000, sapling balance: 3.19990000
Stopping nodes
Cleaning up
Tests successful
--- Success: sprout_sapling_migration.py (158s) ---
```

Fixed by https://github.com/zcash/zcash/pull/4281

Intermittent failures are tracked in https://github.com/zcash/zcash/issues/4276
