### ISSUE TITLE
segfault in libpthread - v2.1.1-1

### ISSUE THREAD

**Issue by josef-v** [zcash/zcash#4419]
We have started seeing crashes of our zcashd, any help is appreciated! 

`Tue Mar 31 00:27:34 2020] zcash-httpworke[6181]: segfault at 478 ip 00007fc67fd5bb40 sp 00007fc666ffc008 error 4 in libpthread-2.24.so[7fc67fd52000+18000]`

This has happened at least 9 times between March 23 and March 31, always the same stack pointer. We are not aware of any change in our configuration.

This issue is observed only on one of our nodes (all nodes running the same docker image).

Zcashd version: v2.1.1-1

We are running our instance in docker based on Debian Stretch image.

Following script is used to build our binaries.
```
make -C ./depends download-linux -j $(nproc) ; \
    HOST=$HOST BUILD=$BUILD NO_PROTON="--enable-proton=no" make \
        -C ./depends \
        V=1 \
        -j $(nproc --ignore=2) ; \
    ./autogen.sh ; \
    ./configure \
        --prefix=$(pwd)/depends/$HOST \
        --host=$HOST \
        --build=$HOST \
        --enable-hardening \
        --enable-tests=no \
        --disable-proton \
        CXXFLAGS="-fwrapv -fno-strict-aliasing -Werror -g"
```

I have uploaded the binaries here https://we.tl/t-C5Icw6gBEe as github's limit is 10MB. Hope someone skilled with GDB will find something.

**Comment by daira** [comment]
Can you obtain a stack trace, please?

Build with `--enable-debug` added to the `./configure` arguments, then run with `gdb --ex=run --args src/zcashd`. If you get to the gdb prompt, enter `bt` and paste the output here.

**Comment by daira** [comment]
Also, please attach the last 500 lines or so of `debug.log` (in the node data directory) before the crash.

**Comment by josef-v** [comment]
Hi daira, thanks for response.

> Can you obtain a stack trace, please?

Ok, I don't have enough experience with this low level debugging, so this question might be a little bit stupid. Is the stack trace which I'll get from core dump the same thing you want? The node is on a production environment so running it in gdb and waiting for segfault is not a thing we want to do.
Getting a core dump and extracting it from it is however a different story.

Here is the log before one of the crashes.
[zcash_debug.log](https://github.com/zcash/zcash/files/4428714/zcash_debug.log)

**Comment by mdr0id** [comment]
@josef-v Providing the core dump file will work. `gdb ./src/zcashd /path-to-core-file` , then provide the prompt with `bt`

**Comment by josef-v** [comment]
Ok, we finally got one!
```
#0  0x00007f40ba3c1b40 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055d4b4df93bb in boost::posix::pthread_mutex_lock (m=0x468) at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:57
#2  boost::recursive_mutex::lock (this=0x468) at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp:108
#3  0x000055d4b4e15d97 in AnnotatedMixin<boost::recursive_mutex>::lock (this=0x468) at sync.h:60
#4  0x000055d4b4e0bb4d in boost::unique_lock<AnnotatedMixin<boost::recursive_mutex> >::lock (this=0x7f40a5d3a540)
    at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/lock_types.hpp:346
#5  0x000055d4b4e0320e in CMutexLock<AnnotatedMixin<boost::recursive_mutex> >::Enter (this=0x7f40a5d3a540, pszName=0x55d4b5aa2c22 "pwalletMain->cs_wallet", 
    pszFile=0x55d4b5aa22f2 "rpc/misc.cpp", nLine=274) at sync.h:116
#6  0x000055d4b4dfc969 in CMutexLock<AnnotatedMixin<boost::recursive_mutex> >::CMutexLock (this=0x7f40a5d3a540, mutexIn=..., pszName=0x55d4b5aa2c22 "pwalletMain->cs_wallet", 
    pszFile=0x55d4b5aa22f2 "rpc/misc.cpp", nLine=274, fTry=false) at sync.h:137
#7  0x000055d4b50a6c21 in z_validateaddress (params=..., fHelp=false) at rpc/misc.cpp:274
#8  0x000055d4b50fdd28 in CRPCTable::execute (this=0x55d4b6203880 <tableRPC>, strMethod="z_validateaddress", params=...) at rpc/server.cpp:449
#9  0x000055d4b51ea251 in HTTPReq_JSONRPC (req=0x7f40980021e0) at httprpc.cpp:183
#10 0x000055d4b5044d9f in boost::detail::function::void_function_invoker2<bool (*)(HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), void, HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::invoke (function_ptr=..., a0=0x7f40980021e0, a1="")
    at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/function/function_template.hpp:117
#11 0x000055d4b51f0e87 in boost::function2<void, HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>::operator() (this=0x7f4098002ce0, 
    a0=0x7f40980021e0, a1="") at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/function/function_template.hpp:764
#12 0x000055d4b51f056b in HTTPWorkItem::operator() (this=0x7f4098002cb0) at httpserver.cpp:51
#13 0x000055d4b51f2073 in WorkQueue<HTTPClosure>::Run (this=0x55d4b6a55ab0) at httpserver.cpp:137
#14 0x000055d4b51ee41a in HTTPWorkQueueRun (queue=0x55d4b6a55ab0) at httpserver.cpp:359
#15 0x000055d4b51fbc31 in boost::_bi::list1<boost::_bi::value<WorkQueue<HTTPClosure>*> >::operator()<void (*)(WorkQueue<HTTPClosure>*), boost::_bi::list0> (this=0x55d4b6a80de0, 
    f=@0x55d4b6a80dd8: 0x55d4b51ee3e7 <HTTPWorkQueueRun(WorkQueue<HTTPClosure>*)>, a=...) at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/bind/bind.hpp:259
#16 0x000055d4b51fbb4e in boost::_bi::bind_t<void, void (*)(WorkQueue<HTTPClosure>*), boost::_bi::list1<boost::_bi::value<WorkQueue<HTTPClosure>*> > >::operator() (this=0x55d4b6a80dd8)
    at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/bind/bind.hpp:1294
#17 0x000055d4b51fb9d9 in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(WorkQueue<HTTPClosure>*), boost::_bi::list1<boost::_bi::value<WorkQueue<HTTPClosure>*> > > >::run (
    this=0x55d4b6a80ca0) at /zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/detail/thread.hpp:120
#18 0x000055d4b55a7deb in thread_proxy ()
#19 0x00007f40ba3bf4a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f40b95d6d0f in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by LarryRuane** [comment]
I will try to find time to look at this; is it still a problem?

**Comment by josef-v** [comment]
I don't think so. We haven't encountered this for a long time (this issue is over a year old?) and no one else has reported it.

**Comment by LarryRuane** [comment]
Thanks, @josef-v, we can reopen if needed.
