### ISSUE TITLE
libfuzzer build fails on boost with AdressSanitizer

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#4901]
During the boost build, it builds some binary that it runs at a later stage of its build process, which causes a build failure because LeakSanitizer detects a leak in whatever that binary is.

**Comment by defuse** [comment]
This failed even with `--sanitizers "undefined"` so somehow address sanitizer is getting in there anyway.

**Comment by daira** [comment]
Tested using [this branch](https://github.com/daira/zcash/tree/fuzzcashd-rebase) with:
```
zcutil/distclean.sh
zcutil/libfuzzer/libfuzzer-build.sh depends --sanitizers "undefined" --coverage --fuzzer CheckBlock V=1
```
Final part of the output:
```
    "llvm-ar"  rc "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread.a" "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/pthread/thread.o" "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/pthread/once.o" "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/future.o"
    "llvm-ranlib" "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread.a"


file /tmp/jam2ede71cc.000
# Generated by Boost 1.74.0

# address-model=64

if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  _BOOST_SKIPPED("libboost_thread.a" "64 bit, need 32")
  return()
endif()

# layout=system

# toolset=clang8

# link=static

if(DEFINED Boost_USE_STATIC_LIBS)
  if(NOT Boost_USE_STATIC_LIBS)
    _BOOST_SKIPPED("libboost_thread.a" "static, Boost_USE_STATIC_LIBS=${Boost_USE_STATIC_LIBS}")
    return()
  endif()
else()
  if(NOT WIN32 AND NOT _BOOST_SINGLE_VARIANT)
    _BOOST_SKIPPED("libboost_thread.a" "static, default is shared, set Boost_USE_STATIC_LIBS=ON to override")
    return()
  endif()
endif()

# runtime-link=shared

if(Boost_USE_STATIC_RUNTIME)
  _BOOST_SKIPPED("libboost_thread.a" "shared runtime, Boost_USE_STATIC_RUNTIME=${Boost_USE_STATIC_RUNTIME}")
  return()
endif()

# runtime-debugging=off

if(Boost_USE_DEBUG_RUNTIME)
  _BOOST_SKIPPED("libboost_thread.a" "release runtime, Boost_USE_DEBUG_RUNTIME=${Boost_USE_DEBUG_RUNTIME}")
  return()
endif()

# threading=multi

# variant=release

if(NOT "${Boost_USE_RELEASE_LIBS}" STREQUAL "" AND NOT Boost_USE_RELEASE_LIBS)
  _BOOST_SKIPPED("libboost_thread.a" "release, Boost_USE_RELEASE_LIBS=${Boost_USE_RELEASE_LIBS}")
  return()
endif()

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "  [x] libboost_thread.a")
endif()

# Create imported target Boost::thread

if(NOT TARGET Boost::thread)
  add_library(Boost::thread STATIC IMPORTED)

  set_target_properties(Boost::thread PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
    INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
  )
endif()

# Target file name: libboost_thread.a

get_target_property(__boost_imploc Boost::thread IMPORTED_LOCATION_RELEASE)
if(__boost_imploc)
  message(SEND_ERROR "Target Boost::thread already has an imported location '${__boost_imploc}', which is being overwritten with '${_BOOST_LIBDIR}/libboost_thread.a'")
endif()
unset(__boost_imploc)

set_property(TARGET Boost::thread APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)

set_target_properties(Boost::thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE CXX
  IMPORTED_LOCATION_RELEASE "${_BOOST_LIBDIR}/libboost_thread.a"
  )

set_target_properties(Boost::thread PROPERTIES
  MAP_IMPORTED_CONFIG_MINSIZEREL Release
  MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
  )

list(APPEND _BOOST_THREAD_DEPS headers)

boost-install.generate-cmake-variant- bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread-variant-static.cmake


common.copy /home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/stage/lib/libboost_thread.a

    cp "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread.a"  "/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/stage/lib/libboost_thread.a"

text-action bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread-variant-static.cmake

    cat "/tmp/jam2ede71cc.000" > "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread-variant-static.cmake"

common.copy /home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/stage/lib/cmake/boost_thread-1.74.0/libboost_thread-variant-static.cmake

    cp "bin.v2/libs/thread/build/clang-linux-8.0.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/libboost_thread-variant-static.cmake"  "/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/stage/lib/cmake/boost_thread-1.74.0/libboost_thread-variant-static.cmake"


=================================================================
==11998==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 90 byte(s) in 1 object(s) allocated from:
    #0 0x3219d3 in malloc (/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/b2+0x3219d3)
    #1 0x289b62 in __interceptor_strndup (/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/b2+0x289b62)
    #2 0x3a1cfd  (/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/b2+0x3a1cfd)
    #3 0x3d603e  (/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/b2+0x3d603e)
    #4 0x3a15d1  (/home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/b2+0x3a15d1)
    #5 0x7f1b504e3e0a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26e0a)

SUMMARY: AddressSanitizer: 90 byte(s) leaked in 1 allocation(s).
make: *** [funcs.mk:247: /home/daira/zecc/zcash/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-d1db79b8e81/./.stamp_built] Error 1
make: Leaving directory '/home/daira/zecc/zcash/depends'
+ die 'Couldn'\''t build dependencies.'
+ echo 'Couldn'\''t' build dependencies.
Couldn't build dependencies.
+ exit -1
```

**Comment by noloader** [comment]
@daira,

If that's a transient failure because some program is not cleaning up before exit, you can use this to suppress it (and continue the build):

```
ASAN_OPTIONS='detect_leaks=0'
export ASAN_OPTIONS
```

Once your build is complete, then unset `ASAN_OPTIONS`.
