### ISSUE TITLE
only load the proof parameters in gtests for tests that need them

### ISSUE THREAD

**Issue by superbaud** [zcash/zcash#5633]
Currently, the proof parameters are loaded in the `main` function of `zcash/src/gtest/main.cpp`. However, every time we execute a "death test", the gtest test framework forks a new process *which will load the proof parameters again*. 

As far as i can tell, no death test depends on the proofs. There are 13 death tests, and loading the proof params takes approximately 7 seconds (`time ./src/zcash-gtest --help`, yes, they're loaded even to print the help message!), so we might be able to save `7*13=91` seconds per test run.

**Comment by superbaud** [comment]
Hah, the delta from my quick-and-dirty patch (which isn't yet compatible with sharding) is `94.37` seconds -- that estimate wasn't far off!

Original `gtest`:  `4*60 + 17.325 = 257.325`
```
real    4m17.325s
user    29m35.588s
sys     0m8.594s
```

Patched version: `2*60 + 42.955 = 162.955`

```
real    2m42.955s
user    22m1.709s
sys     0m5.328s
```

**Comment by superbaud** [comment]
here's the [quick and dirty patch](https://github.com/superbaud/zcash/commits/lazy-load-parameters) if anyone wants to peruse it (it's not even draft PR - worth yet but i wanted to show my work).

**Comment by superbaud** [comment]
i'm not sure where we want to add code to make calling `LoadProofParameters()` twice a no-op -- in that set of commits i have it as a modification to `librustzcash_init_zksnark_params` but i could totally add a global static variable in the C++ code and test it in `LoadProofParameters` itself. Let me know which option y'all prefer!

**Comment by superbaud** [comment]
To quickly get a list of tests that need the parameters, i did:

```
$ grep RUN shuffle_iteration|sort|uniq|cut -f2 -d]|less|sed -e 's/ //' > list_tests
$ time (for test in `cat list_tests`; do ./src/zcash-gtest --gtest_filter=$test;done) > errors 2>&1
$ grep -B1  panic errors > parameter_wanting_tests
```
which gives us
```
[ RUN      ] ChecktransactionTests.HeartwoodAcceptsShieldedCoinbase
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] ChecktransactionTests.HeartwoodEnforcesSaplingRulesOnShieldedCoinbase
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] Joinsplit.FullApiTest
thread '<unnamed>' panicked at 'parameters should have been initialized', src/rust/src/rustzcash.rs:744:14
--
[ RUN      ] MempoolLimitTests.WeightedTxInfoFromTx
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] RecursiveDynamicUsageTests.TestTransactionSaplingToSapling
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] RecursiveDynamicUsageTests.TestTransactionSaplingToTransparent
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] RecursiveDynamicUsageTests.TestTransactionTransparentToSapling
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] TransactionBuilder.ChangeOutput
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] TransactionBuilder.FailsWithNegativeChange
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] TransactionBuilder.SaplingToSapling
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] TransactionBuilder.SaplingToSprout
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] TransactionBuilder.SetFee
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] TransactionBuilder.SproutToSproutAndSapling
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] TransactionBuilder.TransparentToSapling
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] WalletTests.FindMySaplingNotes
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.GetConflictedSaplingNotes
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.MarkAffectedSaplingTransactionsDirty
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:852:51
--
[ RUN      ] WalletTests.NavigateFromSaplingNullifierToNote
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.SaplingNullifierIsSpent
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.SetSaplingNoteAddrsInCWalletTx
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.SpentSaplingNoteIsFromMe
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
--
[ RUN      ] WalletTests.UpdatedSaplingNoteData
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/rust/src/rustzcash.rs:1010:54
```

So let's add a `LoadProofParameters();` to each of those tests.
