### ISSUE TITLE
smoke_tests.py fails due to deprecated RPC commands

### ISSUE THREAD

**Issue by softminus** [zcash/zcash#6611]
On `commit d2d29fb9fefa99ee66b8bc9f265bb51c98f2d643 (HEAD -> version-5.5.0, origin-zcash/version-5.5.0)`, running `./qa/zcash/smoke_tests.py` causes these errors -- we either need to update those invocations to use the replacement commands or delete them:

```
Running stage transaction-chain
===============================

----- 0:00:22.032789 -----
3c  $ zcash-cli getnewaddress 
ERROR: getnewaddress: getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.032840 -----
3d  $ zcash-cli getnewaddress 
ERROR: getnewaddress: getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.032880 -----
3d  $ zcash-cli getnewaddress 
ERROR: getnewaddress: getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.032925 -----
3d  $ zcash-cli getnewaddress 
ERROR: getnewaddress: getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.032963 -----
3d  $ zcash-cli getnewaddress 
ERROR: getnewaddress: getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.033001 -----
3e  $ zcash-cli z_getnewaddress sapling
ERROR: z_getnewaddress: z_getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=z_getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.033041 -----
3f  $ zcash-cli z_getnewaddress sapling
ERROR: z_getnewaddress: z_getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=z_getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.033081 -----
3f  $ zcash-cli z_getnewaddress sapling
ERROR: z_getnewaddress: z_getnewaddress is DEPRECATED and will be removed in a future release

Use z_getnewaccount and z_getaddressforaccount instead, or restart 
with `-allowdeprecated=z_getnewaddress` if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
----- 0:00:22.033176 -----
5a  $ zcash-cli z_listaddresses 
ERROR: z_listaddresses: z_listaddresses is DEPRECATED and will be removed in a future release

Use listaddresses or restart with `-allowdeprecated=z_listaddresses`
if you require backward compatibility.
See https://zcash.github.io/zcash/user/deprecation.html for more information. (code -1)
Traceback (most recent call last):
  File "/home/sasha_work/src/zcash/./qa/zcash/smoke_tests.py", line 743, in <module>
    main()
  File "/home/sasha_work/src/zcash/./qa/zcash/smoke_tests.py", line 705, in main
    results.update(run_stage(s, zcash))
  File "/home/sasha_work/src/zcash/./qa/zcash/smoke_tests.py", line 544, in run_stage
    ret = cmd(zcash)
  File "/home/sasha_work/src/zcash/./qa/zcash/smoke_tests.py", line 338, in transaction_chain
    if ( sapling_zaddr_1 not in zaddrs or
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by softminus** [comment]
```
    # Validate the addresses
    ret = run_cmd(results, '5c', zcash, 'z_validateaddress', [sapling_zaddr_1])
    if not ret['isvalid'] or ret['type'] != 'sapling':
        results['5c'] = False

```

also this fails, since what's returned looks like:

```
sasha_work@myouren:~/src/zcash$ ./src/zcash-cli -datadir=$HOME/.zcash-testnet -rpcuser=st -rpcpassword=st z_validateaddress ztestsapling1ddae94c086wjlcpmlrp3ghlg7j8mjlx0ceud4mdqgutkf5nscldaqq0jmkjpvqu3dlmxwdhq58m
{
  "isvalid": true,
  "address": "ztestsapling1ddae94c086wjlcpmlrp3ghlg7j8mjlx0ceud4mdqgutkf5nscldaqq0jmkjpvqu3dlmxwdhq58m",
  "address_type": "sapling",
  "diversifier": "6b7b92d70f3e9d2fe03bf8",
  "diversifiedtransmissionkey": "67f66f910316a4ddf201d0dbc770d2641747a0edda78c6cf7cb98ff4e85f14c3",
  "ismine": true
}
```

**Comment by softminus** [comment]
Adding the `-allowdeprecated` command-line options and fixing the `'type'` to `'addresstype'` we run into another problem:

```
    # Validate the addresses
    ret = run_cmd(results, '5c', zcash, 'z_validateaddress', [sapling_zaddr_1])
    if not ret['isvalid'] or ret['type'] != 'sapling':
        results['5c'] = False
```

**Comment by softminus** [comment]
Straightforwardly avoiding using deprecated RPC commands in`smoke_tests.py` doesn't work if we create an account, and instead of running `getnewaddress` and `z_getnewaddress` we create a UA and extract the `p2pkh` and `sapling` components 

```python

def generate_ua_address(results, case, zcash, account_number, address_types):
    ret = run_cmd(results, case, zcash, 'z_getaddressforaccount', [account_number, address_types])
    print("created address:", ret['address'])
    return ret['address']

def generate_address(results, case, zcash, account_number, address_type):
    if address_type == ["p2pkh"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["p2pkh", "sapling"])
        taddr_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["p2pkh"]
        return taddr_receiver
    elif address_type == ["non_ua_sapling"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["sapling"])
        sapling_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["sapling"]
        return sapling_receiver
    else:
        full_ua = generate_ua_address(results, case, zcash, account_number, address_type)
        return full_ua

```

along with using them

```python

    taddr_1 = generate_address(results, "3c", zcash, account_number, ["p2pkh"])
    taddr_2 = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    taddr_3 = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    taddr_4 = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    taddr_5 = generate_address(results, "3d", zcash, account_number, ["p2pkh"])

    sapling_zaddr_1 = generate_address(results, "3e", zcash, account_number, ["non_ua_sapling"])
    sapling_zaddr_2 = generate_address(results, "3f", zcash, account_number, ["non_ua_sapling"])
    sapling_zaddr_3 = generate_address(results, "3f", zcash, account_number, ["non_ua_sapling"])
```

since we run into an error every time we try and use these UA-derived addresses to send from:

```
#
# Starting transaction chain
#

----- 0:07:18.629874 -----
4f : z_sendmany ['tmTgHVMeZgzYWxQsqPafR67Xm6mVC5MoJtL', [{'address': 'ztestsapling1hpwqdjnwvwxc7yvtwxfusmntuk6x37rg7elwke8t4qlkzqfte4epm9aa7lr4x8dae5pnyyu2g6z', 'amount': Decimal('0.99999000')}], 1, Decimal('0.00001'), 'AllowRevealedSenders']
ERROR: z_sendmany: Invalid from address: is a bare receiver from a Unified Address in this wallet. Provide the UA as returned by z_getaddressforaccount instead. (code -5)
----- 0:07:18.630707 -----
```

Changing the above code to instead read:

```python
def generate_ua_address(results, case, zcash, account_number, address_types):
    ret = run_cmd(results, case, zcash, 'z_getaddressforaccount', [account_number, address_types])
    print("created address:", ret['address'])
    return ret['address']

def generate_address(results, case, zcash, account_number, address_type):
    if address_type == ["p2pkh"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["p2pkh", "sapling"])
        taddr_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["p2pkh"]
        return (taddr_receiver, from_ua)
    elif address_type == ["non_ua_sapling"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["sapling"])
        sapling_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["sapling"]
        return (sapling_receiver, from_ua)
    else:
        full_ua = generate_ua_address(results, case, zcash, account_number, address_type)
        return (full_ua, full_ua)

```

and invoking it with:

```python
    account_number  = run_cmd(results, '3aa', zcash, 'z_getnewaccount')["account"]

    (taddr_1, taddr_1_from) = generate_address(results, "3c", zcash, account_number, ["p2pkh"])
    (taddr_2, taddr_2_from) = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    (taddr_3, taddr_3_from) = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    (taddr_4, taddr_4_from) = generate_address(results, "3d", zcash, account_number, ["p2pkh"])
    (taddr_5, taddr_5_from) = generate_address(results, "3d", zcash, account_number, ["p2pkh"])

    (sapling_zaddr_1, sapling_zaddr_1_from) = generate_address(results, "3e", zcash, account_number, ["non_ua_sapling"])
    (sapling_zaddr_2, sapling_zaddr_2_from) = generate_address(results, "3f", zcash, account_number, ["non_ua_sapling"])
    (sapling_zaddr_3, sapling_zaddr_3_from) = generate_address(results, "3f", zcash, account_number, ["non_ua_sapling"])
```

and replacing each of the variables with its `_from` equivalent as the `fromaddress` parameter in the `z_sendmany` calls, we run into a more subtle problem:

```
----- 0:02:38.894701 -----
4h : z_sendmany ['utest175veup8xns0dxvx590k3nafdq80w79x0clkkt0ltzj773cuwsyydcfrwf4quyapcngh8rx67qx0v8u2ns2wh57pxkyz9c4d67cnmelmd', [{'address': 'ztestsapling15aselas5ecluvadp0afefdmfpngddms02ujlpch7r3v983djkx0494skvnqyfrfg2ekdq6nunn2', 'amount': Decimal('0.69996000')}], 1, Decimal('0.00001'), 'FullPrivacy']
opid-cf2dd594-f096-4e21-b374-ea3995465d7b

Waiting for async operation opid-cf2dd594-f096-4e21-b374-ea3995465d7b
Operation failed
Could not send to the Sapling shielded pool without spending non-Sapling funds, which would reveal transaction amounts. THIS MAY AFFECT YOUR PRIVACY. Resubmit with the `privacyPolicy` parameter set to `AllowRevealedAmounts` or weaker if you wish to allow this transaction to proceed anyway.
```

I believe this is because the previous transaction:

```python
('4e', taddr_1_from, [(taddr_2, taddr_balance - LEGACY_DEFAULT_FEE)], "AllowFullyTransparent")
```

pulls from the Sapling notes in `taddr_1_from`, which depletes enough Sapling coins such that `4h` later fails.

We change the address generation code to instead request `["orchard", "p2pkh"]` which will prevent the t-addr UAs from containing a Sapling endpoint:

```python
def generate_address(results, case, zcash, account_number, address_type):
    if address_type == ["p2pkh"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["p2pkh", "orchard"])
        taddr_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["p2pkh"]
        return (taddr_receiver, from_ua)
    elif address_type == ["non_ua_sapling"]:
        from_ua = generate_ua_address(results, case, zcash, account_number, ["sapling"])
        sapling_receiver = run_cmd(results, case, zcash, 'z_listunifiedreceivers', [from_ua])["sapling"]
        return (sapling_receiver, from_ua)
    else:
        full_ua = generate_ua_address(results, case, zcash, account_number, address_type)
        return (full_ua, full_ua)
```

and it's running now and the `4h` transaction didn't fail:

```
4h : z_sendmany ['utest1whjgs0u34sepsg0489cgeqhv2fdv6fsu7a8g83sm7myfujwzrecg7v4gxal005t4tfnkazq939dg3vwjg3a9fm4gkep23wdw7y565gvm', [{'address': 'ztestsapling1usf2sxte8s8g04w5qxpckdxurlkc06s7agjjzpl9dfkglj7z22y55d58mmylcgavhz6m7tu0qpu', 'amount': Decimal('0.69996000')}], 1, Decimal('0.00001'), 'FullPrivacy']
opid-03e8be16-cc05-4d2c-adac-bbe96f4d96e0

Waiting for async operation opid-03e8be16-cc05-4d2c-adac-bbe96f4d96e0
txid: 6f6ee97a9a7d4b7e065822934d78a99e847fb9dbb0c6bea38692dc1ff0de6261
Waiting for funds to tmGDbiyiM4znCGU9e2LADwuKvEhKhJ8vaq6...
Expecting: 0.29999000; Unconfirmed Balance: 0.29999000
```

**Comment by softminus** [comment]
This does work better, but the `z_mergetoaddress`es fail:

```
4ee: z_mergetoaddress [['tmGo65jyPMjgZeW79zv782yEQdtoq7cS51Y', 'ztestsapling1z9c4x8yucthywpx72pp5up78usp3s3xnzh3fw6qyw2n385jnu4ce5svyamdfzr6x32plqsyv57n'], 'ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm', Decimal('0.00001'), None, None, None, 'AllowRevealedSenders']
{'remainingUTXOs': 0, 'remainingTransparentValue': 0.0, 'remainingNotes': 0, 'remainingShieldedValue': 0.0, 'mergingUTXOs': 1, 'mergingTransparentValue': 0.1, 'mergingNotes': 1, 'mergingShieldedValue': 0.1, 'opid': 'opid-9a57d3e5-0466-439f-969d-ee08da7792ba'}

Waiting for async operation opid-9a57d3e5-0466-439f-969d-ee08da7792ba
txid: f11e292416c3e84375b7ba07f9a41a074e088bb797a7a218251f3962a20e43dc
Waiting for funds to ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm...
Expecting: 0.69992000; Unconfirmed Balance: 0.39998000
WARNING: Unconfirmed balance does not match expected balance
Received 0.39998000
```
and
```
----- 0:27:08.245064 -----
4bb: z_mergetoaddress [['tmBg48XZFN1h9hScUX4iCx1xuJ5LFQv7R2w', 'tmTcnpoLFeiArw2sNfoybz5ctqi3WWLuzvC'], 'ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm', Decimal('0.00001'), None, None, None, 'AllowRevealedSenders']
{'remainingUTXOs': 0, 'remainingTransparentValue': 0.0, 'remainingNotes': 0, 'remainingShieldedValue': 0.0, 'mergingUTXOs': 2, 'mergingTransparentValue': 0.2, 'mergingNotes': 0, 'mergingShieldedValue': 0.0, 'opid': 'opid-89312450-0c75-4e58-9197-4cfacea8e91a'}

Waiting for async operation opid-89312450-0c75-4e58-9197-4cfacea8e91a
txid: 232cb497b5c81cf971964fc10584d0ae97f95583999b80e0c883b19ce2762302
Waiting for funds to ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm...
Expecting: 0.69990000; Unconfirmed Balance: 0.59997000
WARNING: Unconfirmed balance does not match expected balance
Received 0.59997000
Waiting for funds to ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm to receive 4 confirmations...
Expecting: 0.59997000; Unconfirmed Balance: 0.59997000
Received 0.59997000
----- 0:32:47.807945 -----
   : z_mergetoaddress [['ztestsapling1z9c4x8yucthywpx72pp5up78usp3s3xnzh3fw6qyw2n385jnu4ce5svyamdfzr6x32plqsyv57n', 'ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm', 'ztestsapling1df60p5ul45e4rf7lx7j97p7kjhf9e8maqew4gcweyq7veprsfs42gllzlq9tz3hwwry5qawm3ju'], 'tmSmAxoLXL2BXL2PHSakjwBTzNqgpBz1qSZ', Decimal('0.00001'), None, None, None, 'AllowRevealedRecipients']
{'remainingUTXOs': 0, 'remainingTransparentValue': 0.0, 'remainingNotes': 0, 'remainingShieldedValue': 0.0, 'mergingUTXOs': 0, 'mergingTransparentValue': 0.0, 'mergingNotes': 3, 'mergingShieldedValue': 0.59997, 'opid': 'opid-9aa010e3-d067-4ade-94ad-1ec1343b870b'}

Waiting for async operation opid-9aa010e3-d067-4ade-94ad-1ec1343b870b
txid: a91e95f8b2add847ec43902c2f1b396ea9d47b83cd6ad7db69e2c391f3403da4
Waiting for funds to tmSmAxoLXL2BXL2PHSakjwBTzNqgpBz1qSZ...
Expecting: 0.99986000; Unconfirmed Balance: 0.89993000
WARNING: Unconfirmed balance does not match expected balance
```
and
```
---- 0:17:20.145006 -----
4gg: z_mergetoaddress [['ztestsapling1z9c4x8yucthywpx72pp5up78usp3s3xnzh3fw6qyw2n385jnu4ce5svyamdfzr6x32plqsyv57n', 'ztestsapling1df60p5ul45e4rf7lx7j97p7kjhf9e8maqew4gcweyq7veprsfs42gllzlq9tz3hwwry5qawm3ju'], 'ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm', Decimal('0.00001'), None, None, None, 'FullPrivacy']
{'remainingUTXOs': 0, 'remainingTransparentValue': 0.0, 'remainingNotes': 0, 'remainingShieldedValue': 0.0, 'mergingUTXOs': 0, 'mergingTransparentValue': 0.0, 'mergingNotes': 2, 'mergingShieldedValue': 0.2, 'opid': 'opid-0d8dd3d4-41d1-4770-83e7-9de46f56b243'}

Waiting for async operation opid-0d8dd3d4-41d1-4770-83e7-9de46f56b243
txid: 13634ebe36909fbbfb820728886711ab2e2ae92f916b47af5afd62840c9e8125
Waiting for funds to tmGCMXHg8WFikw8ANrzp6nstfbfBe2hmc4h to receive 4 confirmations...
Expecting: 0.10000000; Unconfirmed Balance: 0.10000000
Received 0.10000000
Waiting for funds to tmGo65jyPMjgZeW79zv782yEQdtoq7cS51Y to receive 4 confirmations...
Expecting: 0.19998000; Unconfirmed Balance: 0.19998000
Received 0.19998000
----- 0:17:21.188536 -----
   : z_mergetoaddress [['tmGCMXHg8WFikw8ANrzp6nstfbfBe2hmc4h', 'tmGo65jyPMjgZeW79zv782yEQdtoq7cS51Y'], 'tmSmAxoLXL2BXL2PHSakjwBTzNqgpBz1qSZ', Decimal('0.00001'), None, None, None, 'AllowFullyTransparent']
{'remainingUTXOs': 0, 'remainingTransparentValue': 0.0, 'remainingNotes': 0, 'remainingShieldedValue': 0.0, 'mergingUTXOs': 2, 'mergingTransparentValue': 0.29998, 'mergingNotes': 0, 'mergingShieldedValue': 0.0, 'opid': 'opid-7d71ca65-c163-4a93-a6c3-8810940ba1cf'}

Waiting for async operation opid-7d71ca65-c163-4a93-a6c3-8810940ba1cf
txid: 599da7fdd712778d07b806092235191c7bd38e9339894892ce59b7705e36987f
Waiting for funds to ztestsapling1rtf4h9vlh4eneusydd6669jqgm8skghz8warzlz2saa3rdw4t5pqjv84x0f4fpjtjt4kqcjlxlm...
Expecting: 0.69994000; Unconfirmed Balance: 0.19999000
WARNING: Unconfirmed balance does not match expected balance
Received 0.19999000
Waiting for funds to tmSmAxoLXL2BXL2PHSakjwBTzNqgpBz1qSZ...
Expecting: 0.29997000; Unconfirmed Balance: 0.29997000
Received 0.29997000
----- 0:18:01.455589 -----
```

Unfortunately, `z_mergetoaddress` doesn't work with UAs yet, so it doesn't seem like there's an easy way to go from here
