### ISSUE TITLE
thread '<unnamed>' panicked at 'This note has been marked as one of ours.', src/rust/src/wallet.rs:739:18

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#6745]
### Describe the issue
zcashd crashes at startup, did not have an issue last time I started it... perhaps sometime last week.

### Actual behaviour + errors

`thread '<unnamed>' panicked at 'This note has been marked as one of ours.', src/rust/src/wallet.rs:739:18`

### The version of Zcash you were using:
v5.6.1

### Any extra information that might be useful in the debugging process.
I don't see anything worth noting in debug log...

```
2023-07-27T19:24:39.911795Z  INFO Init: main: Opening LevelDB in /home/user/.zcash/blocks/index
2023-07-27T19:24:39.981706Z  INFO Init: main: Opened LevelDB successfully
2023-07-27T19:24:39.981744Z  INFO Init: main: Opening LevelDB in /home/user/.zcash/chainstate
2023-07-27T19:24:40.058701Z  INFO Init: main: Opened LevelDB successfully
2023-07-27T19:25:33.846452Z  INFO Init: main: LoadBlockIndexDB: last block file = 2007
2023-07-27T19:25:33.851156Z  INFO Init: main: LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=446, size=48318302, heights=2150029...2150486, time=2023-07-09...2023-07-09)
2023-07-27T19:25:33.851202Z  INFO Init: main: Checking all blk files are present...
2023-07-27T19:25:34.663494Z  INFO Init: main: LoadBlockIndexDB: transaction index disabled
2023-07-27T19:25:34.663547Z  INFO Init: main: LoadBlockIndexDB: insight explorer disabled
2023-07-27T19:25:34.663553Z  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled
2023-07-27T19:25:36.650492Z  INFO Init: main: LoadBlockIndexDB: hashBestChain=0000000001077a5ba902364f1b021823803cd861152a9c292d6f43686e980310 height=2150486 date=2023-07-09 23:51:01 progress=0.962001
2023-07-27T19:25:36.678007Z  INFO Init: main: init message: Rewinding blocks if needed...
2023-07-27T19:25:48.181871Z  INFO Init: main: init message: Verifying blocks...
2023-07-27T19:25:48.181931Z  INFO Init: main: Verifying last 288 blocks at level 3
2023-07-27T19:25:53.296272Z  INFO Init: main: No coin database inconsistencies in last 289 blocks (1391 transactions)
2023-07-27T19:25:53.297754Z  INFO Init: main:  block index           73390ms
2023-07-27T19:25:53.297827Z  INFO Init: main: init message: Loading wallet...
2023-07-27T19:25:55.759308Z  INFO Init: main: nFileVersion = 5060150
2023-07-27T19:25:55.759410Z  INFO Init: main: Keys: 217 plaintext, 0 encrypted, 217 w/ metadata, 217 total
2023-07-27T19:25:55.759460Z  INFO Init: main: ZKeys: 13 plaintext, 0 encrypted, 13 w/metadata, 13 total
2023-07-27T19:25:55.764912Z  INFO Init: main:  wallet                 2467ms
```

**Comment by zookozcash** [comment]
Thanks for the bug report, Paige!

**Comment by zookozcash** [comment]
Paige, I'm sorry that you're having this problem. We've triaged this issue and for your information we're not currently prioritising supporting the wallet within zcashd because we're prioritising our mobile SDKs so that users of Nighthawk, Edge, and Unstoppable regain access to their funds. (Here's our most recent update on that: https://forum.zcashcommunity.com/t/all-ecc-teams-focused-on-wallet-performance/42860/112 Again, I'm sorry that the zcashd wallet is not working for you right now.
